TRUNCATE TAbLE [dbo].[Fact Contract Table]
TRUNCATE TAbLE [dbo].[Dim NearestMetro Table]
TRUNCATE TAbLE [dbo].[DimAreaTable]
TRUNCATE TAbLE [dbo].[DimearesMall Table]
TRUNCATE TAbLE [dbo].[DimContractTypeTable]
TRUNCATE TAbLE [dbo].[DimEjaribuspropertytype Table]
TRUNCATE TAbLE [dbo].[DimEjariproperysubtype Table]
TRUNCATE TAbLE [dbo].[DimEjariproperytype Table]
TRUNCATE TAbLE [dbo].[DimMasterProjectTable]
TRUNCATE TAbLE [dbo].[DimNearesLandMarkTable]
TRUNCATE TAbLE [dbo].[DimProject Table]
TRUNCATE TAbLE [dbo].[DimProperyUsage Table]
TRUNCATE TAbLE [dbo].[DimTenant Table]
